### ISSUE TITLE
Переменная halberdier внутри cutscene не изменяет значение

### ISSUE THREAD

**Issue by Irremann** [instead-hub/stead3-modules#1]
-- $Name: Тест$
-- $Version: 0.01$
-- $Author: Irremann$

require 'cutscene'

global {
	halberdier = 22;
};

main = cutscene {
	nam = 'main';
	disp = false;
	decor = function()
		pn (halberdier..'^[cut]');
		pn "[code halberdier = 1;]";
		pn (halberdier);
	end;
};

**Comment by hugeping** [comment]
Некорректный пример. Сначала выполнится код: pn (halberdier); (на этапе обработки decor)
А уже после вывода на экран decor -- выполнится pn "[code halberdier = 1;]";
Если вывести свою переменную после, например, перехода. Или так: pn "[code pn(halberdier)]"  будет 1.

main = cutscene {
nam = 'main';
disp = false;
decor = function()
    pn "[code halberdier = 1;]";
    pn "[code pn(halberdier)]";
end;
};
