### ISSUE TITLE
Местоимения после предлогов

### ISSUE THREAD

**Issue by cheshiren** [instead-hub/stead3-modules#4]
Не обрабатываются местоимения после предлогов: «по нему», «о нём», «с ним» и т.п.

**Comment by hugeping** [comment]
Это то что сегодня говорили? Поговорить с ним? Или другая ситуация? Конкретный пример приведи пожалуйста

**Comment by hugeping** [comment]
Если оно, то в последней версии должно работать.

**Comment by cheshiren** [comment]
Да, Пётр, оно. В новой версии всё работает.
