### ISSUE TITLE
Метапарсер не поддерживает tiny_instead

### ISSUE THREAD

**Issue by Oreolek** [instead-hub/stead3-modules#7]
Метапарсер был бы отличным кандидатом на запуск в консоли, но сам модуль не запускается в `tiny-instead`. Ругается на отсутствие `instead.mouse_filter`, `instead.gamepath`. Прошу исправить.

**Comment by hugeping** [comment]
Сделал несколько изменений в stead3-modules и в instead (tiny).
Теперь в появился вариант tiny-mp в котором игры МП3 должны работать.
